[build]
  # Install dependencies and run your CSS+JS build
  command   = "npm install && npm run build"
  # Serve directly from the project root
  publish   = "./"
  # (Optional) Netlify Functions folder
  functions = "netlify/functions"

[[redirects]]
  from   = "/old-path"
  to     = "/new-path"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "DENY"
    X-XSS-Protection       = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy        = "no-referrer-when-downgrade"
